title: Dr Paddy Tobias
url: "https://paddytobias.github.io"
baseurl: "/resume"

markdown: kramdown

tracking_id: UA-120932006-1

footer: yes
footer_url: "mailto:paddytobias@me.com"
footer_text: "<p>0403 328 864</p><p>paddytobias@me.com</p>"

sass:
    style: compressed
    sass_dir: _sass

