title: Dr Paddy Tobias
url: "https://paddytobias.github.io"
baseurl: "/resume"

markdown: kramdown

tracking_id: UA-120932006-1

footer: yes
footer_text: "<center><p><a href="paddytobias.github.io/resume/">paddytobias.github.io/resume/</a></p><p>paddytobias@me.com</p><p>0403 328 864</p></center>"

sass:
    style: compressed
    sass_dir: _sass

