title: Dr Paddy Tobias
url: "https://paddytobias.github.io"
baseurl: "/resume"

markdown: kramdown

tracking_id: UA-120932006-1

footer: yes
footer_url: "https://paddytobias.github.io/resume/"
footer_text: "<p>Resumé of Dr Paddy Tobias</p><p>[paddytobias@me.com](mailto:paddytobias@me.com)</p><p>[+61 403 328 864](tel:+61-403328864)</p>"

sass:
    style: compressed
    sass_dir: _sass
