title: Dr Paddy Tobias
url: "https://paddytobias.github.io"
baseurl: "/resume"

markdown: kramdown

tracking_id: UA-120932006-1

footer: yes
footer_url: "https://paddytobias.github.io/resume/"
footer_text: "<p>Resumé of Dr Paddy Tobias</p><p><a href="mailto:paddytobias@me.com">paddytobias@me.com</a></p><p><a href="tel:+61403328864">0403 328 864</a></p>"

sass:
    style: compressed
    sass_dir: _sass

