title: Dr Paddy Tobias
url: "https://paddytobias.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: UA-120932006-1

footer: yes
footer_url: "mailto:paddytobias@me.com"
footer_text: "<center><p>paddytobias.github.io</p><p>paddytobias@me.com</p></center>"

sass:
    style: compressed
    sass_dir: _sass

